import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/navbar/Navbar";
import Provider from "@/lib";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`} theme-data='light'
    >
      <body className="min-h-full container mx-auto flex flex-col">
        <Provider>
            <Navbar/>
        <main>{children} </main>

         <ToastContainer position="top-center"/>
        </Provider>

        </body>
    </html>
  );
}
